//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestEol {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestEol.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to param(
        ///    [parameter(Mandatory=$true)]
        ///    $HttpContext,
        ///    [parameter(ValueFromPipeline=$true,Mandatory=$false)]
        ///    $pipelineInput
        ///)
        ///$Request = $HttpContext.Request
        ///$Response = $HttpContext.Response
        ///$Response.StatusCode = 200
        ///
        ///if ( $pipelineInput )
        ///{
        ///    $Response.ContentType = &apos;application/json&apos;
        ///    $pipelineInput | ConvertTo-JSON
        ///}
        ///else
        ///{
        ///    $Response.ContentType = &apos;text/plain&apos;
        ///    $ContentRoot
        ///    &apos; &apos;
        ///    $Request.Method
        ///    &apos; &apos;
        ///    $Request.Path.Value
        ///    &apos; &apos;
        ///    $Request.QueryString.Value
        ///    &quot;`n&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Handler {
            get {
                return ResourceManager.GetString("Handler", resourceCulture);
            }
        }
    }
}
